/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "primeToken.h"

bool_t
xdr_Tkn (XDR *xdrs, Tkn *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->_numberOfHops))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->_timeOfCreation))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_nextInteger))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_numberOfPrimesFound))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->_highestPrimeFound))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Token (XDR *xdrs, Token *objp)
{
	register int32_t *buf;

	 if (!xdr_Tkn (xdrs, objp))
		 return FALSE;
	return TRUE;
}
