/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "primeToken.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Token *
start_prime_computation_1(Token *argp, CLIENT *clnt)
{
	static Token clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, START_PRIME_COMPUTATION,
		(xdrproc_t) xdr_Token, (caddr_t) argp,
		(xdrproc_t) xdr_Token, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
